name: Rust-Non-Windows

on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BUILD_TYPE: Release

jobs:
  build_and_publish:
  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    
        # Check out the repository (basically downloads the source code)
      - uses: actions/checkout@v3
      
      
        # Install gexiv2 for rexiv2
      - name: gexiv2 (macos-latest)
        if: matrix.os == 'macos-latest'
        run: brew install gexiv2
        
      - name: gexiv2 (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libgexiv2-dev
            
            
      - name: Build
        run: cargo build --release --verbose

      - name: Create Artifact
        run: |
          mkdir ${{ matrix.os }}-release
          cp target/release/mandelbrot-rust ${{ matrix.os }}-release/      
          
      - name: ZIP Artifact
        run: |
          zip -r ${{ matrix.os }}.zip ${{ matrix.os }}-release/
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}.zip
          


  release:
    name: "Release"
    needs: build_and_publish
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/download-artifact@v2
      
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest (development) Build"
          files: |
            ubuntu-latest/ubuntu-latest.zip
            macos-latest/macos-latest.zip
